name: axiom
description: A CLI tool that converts JSON into gorgeous, typesafe code in dart
version: 0.1.0
repository: https://github.com/knowbee/axiom

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  args: ^2.3.1
  dart_style: ^2.2.4
  mason_logger: ^0.2.0
  pub_updater: ">=0.2.1 <0.4.0"
  recase: ^4.1.0

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0

executables:
  axiom:
